export function toWordDoc(text, title = "Document") {
  // Convert markdown-style text → clean HTML for Word
  const mdToHtml = (raw) => {
    let out = "";
    let inUl = false, inOl = false;
    const closeList = () => { if(inUl){out+="</ul>";inUl=false;} if(inOl){out+="</ol>";inOl=false;} };
    const esc = s => s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
    const inline = s => esc(s)
      .replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>")
      .replace(/\*([^*]+)\*/g,"<em>$1</em>")
      .replace(/`([^`]+)`/g,"<code>$1</code>");

    for (const line of raw.split("\n")) {
      const t = line.trim();
      if (!t) { closeList(); out += "<br>"; continue; }
      if (t.startsWith("## ")) { closeList(); out+=`<h2>${inline(t.slice(3))}</h2>`; continue; }
      if (t.startsWith("# "))  { closeList(); out+=`<h1>${inline(t.slice(2))}</h1>`; continue; }
      if (/^[✅☐⚠🔴🟡🟢]/.test(t)){
        closeList();
        const emoji = t.charAt(0); const rest = t.slice(1).trim();
        out+=`<p class="check"><span class="em">${emoji}</span> ${inline(rest)}</p>`;
        continue;
      }
      if (t.startsWith("- ")||t.startsWith("• ")){
        if(inOl){out+="</ol>";inOl=false;}
        if(!inUl){out+="<ul>";inUl=true;}
        out+=`<li>${inline(t.replace(/^[-•]\s*/,""))}</li>`; continue;
      }
      if (/^\d+\./.test(t)){
        if(inUl){out+="</ul>";inUl=false;}
        if(!inOl){out+="<ol>";inOl=true;}
        out+=`<li>${inline(t.replace(/^\d+\.\s*/,""))}</li>`; continue;
      }
      if (t.startsWith("⚠")) { closeList(); out+=`<p class="disclaimer">${inline(t)}</p>`; continue; }
      if (/^---+$/.test(t))   { closeList(); out+="<hr>"; continue; }
      closeList();
      out+=`<p>${inline(t)}</p>`;
    }
    closeList();
    return out;
  };

  const bodyHtml = mdToHtml(text);
  const dateStr  = new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"});

  return `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office'
      xmlns:w='urn:schemas-microsoft-com:office:word'
      xmlns='http://www.w3.org/TR/REC-html40'>
<head>
<meta charset='utf-8'>
<title>${title}</title>
<!--[if gte mso 9]>
<xml><w:WordDocument><w:View>Print</w:View><w:Zoom>90</w:Zoom><w:DoNotOptimizeForBrowser/></w:WordDocument></xml>
<![endif]-->
<style>
  @page WordSection1 { size:21cm 29.7cm; margin:2.54cm 2.54cm 2.54cm 2.54cm; mso-header-margin:35.4pt; mso-footer-margin:35.4pt; mso-paper-source:0; }
  div.WordSection1 { page:WordSection1; }
  body  { font-family:Calibri,sans-serif; font-size:11pt; color:#1A1A2E; line-height:1.6; }
  h1    { font-family:'Cormorant Garamond',Garamond,serif; font-size:22pt; font-weight:700; color:#0B0C11; margin:0 0 4pt; letter-spacing:2pt; }
  h2    { font-family:Calibri,sans-serif; font-size:10pt; font-weight:700; color:#555; margin:18pt 0 6pt; text-transform:uppercase; letter-spacing:1pt; border-bottom:1pt solid #DDD; padding-bottom:4pt; mso-border-bottom-alt:solid #DDD .5pt; }
  p     { margin:0 0 7pt; font-size:11pt; }
  ul,ol { margin:4pt 0 8pt 18pt; padding:0; }
  li    { margin:3pt 0; font-size:11pt; }
  strong{ font-weight:700; }
  em    { font-style:italic; }
  code  { font-family:'Courier New',monospace; font-size:10pt; background:#F5F5F5; padding:1pt 3pt; }
  hr    { border:none; border-top:1pt solid #DDD; margin:12pt 0; }
  .meta { font-size:9pt; color:#888; margin-bottom:14pt; }
  .check{ margin:3pt 0; font-size:11pt; }
  .em   { font-size:13pt; }
  .disclaimer { background:#FFF8E7; border-left:3pt solid #F0A844; padding:7pt 10pt; margin:14pt 0 4pt; font-size:10pt; color:#7A6020; mso-border-left-alt:solid #F0A844 2.25pt; }
  .footer{ margin-top:22pt; padding-top:8pt; border-top:1pt solid #EEE; font-size:8.5pt; color:#AAA; mso-border-top-alt:solid #EEE .5pt; }
  .logo { font-size:9pt; color:#D4233A; font-weight:700; letter-spacing:1pt; }
</style>
</head>
<body>
<div class="WordSection1">
<h1>${title.toUpperCase()}</h1>
<p class="meta">
  <span class="logo">ASTREYA</span>&nbsp;&nbsp;Indian Legal AI&nbsp;&nbsp;|&nbsp;&nbsp;Generated on ${dateStr}&nbsp;&nbsp;|&nbsp;&nbsp;Confidential — For Legal Use Only
</p>
<hr>
${bodyHtml}
<div class="footer">
  This document was generated by <strong>Astreya</strong> — an AI-powered Indian Legal Intelligence Platform. All content must be verified against primary sources (SCC Online, Manupatra, IndianKanoon) before reliance. This output does not constitute legal advice. Consult a qualified advocate before acting on any information herein.
</div>
</div>
</body>
</html>`;
}

export function downloadDoc(htmlStr, filename) {
  const blob = new Blob(["\ufeff", htmlStr], { type:"application/msword;charset=utf-8" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename.endsWith(".doc")?filename:filename+".doc";
  document.body.appendChild(a); a.click();
  setTimeout(()=>{ document.body.removeChild(a); URL.revokeObjectURL(url); }, 100);
}
