/** Default matters seeded for a new workspace (mirrors demo data in the UI). */
export const SEED_MATTERS = [
  {
    code: "AST-2026-0042",
    label: "ABC Corp v. XYZ Ltd",
    type: "Commercial",
    status: "active" as const,
    court: "Bombay High Court",
    desc: "Commercial dispute — breach of service agreement. Hearing listed for 14 May 2026.",
    tasks: 3,
  },
  {
    code: "AST-2026-0039",
    label: "Rajan Kapoor – Bail",
    type: "Criminal",
    status: "urgent" as const,
    court: "Sessions Court, Delhi",
    desc: "Anticipatory bail application under S.438 CrPC. Hearing tomorrow.",
    tasks: 5,
  },
  {
    code: "AST-2026-0031",
    label: "Infosys – NDA Review",
    type: "Corporate",
    status: "review" as const,
    court: "N/A",
    desc: "NDA risk review and redlining for proposed partnership with vendor.",
    tasks: 1,
  },
  {
    code: "AST-2026-0028",
    label: "TaxCo GST Dispute",
    type: "Tax",
    status: "pending" as const,
    court: "GST Appellate Authority",
    desc: "Appeal against GST demand of ₹42L — input tax credit disallowance.",
    tasks: 2,
  },
  {
    code: "AST-2026-0019",
    label: "Mehta Family Trust",
    type: "Civil",
    status: "active" as const,
    court: "City Civil Court",
    desc: "Partition suit — disputed ancestral property in Pune.",
    tasks: 0,
  },
  {
    code: "AST-2026-0011",
    label: "StartupX – ESOP Plan",
    type: "Corporate",
    status: "closed" as const,
    court: "N/A",
    desc: "ESOP scheme drafting and Companies Act compliance. Matter closed.",
    tasks: 0,
  },
];
